name: Save PR Number

on:
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    save-pr-number:
        runs-on: ubuntu-latest
        steps:
            - name: Save PR number
              env:
                  PR_NUMBER: ${{ github.event.number }}
              run: echo $PR_NUMBER > pr_number.txt

            - uses: actions/upload-artifact@v3
              with:
                  name: pr_number
                  path: pr_number.txt
